name: Tests

on:
  pull_request:
    branches: [main]

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'try-a-ting'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - run: node index.mjs
